### ISSUE TITLE
exporting juju bundles from jujucharms.com is not readable via python yaml

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#459]
Our issue came up when a user wanted to export a custom bundle from juju-gui and place it inside a conjure-up spell to be used. The problem comes with then exported bundle showing the following annotations:

```
services: 
  easyrsa: 
    charm: "cs:~containers/easyrsa-8"
    num_units: 1
    annotations: 
      "gui-x": "450"
      "gui-y": "550"
    to: 
      - "0"
  etcd: 
    charm: "cs:~containers/etcd-29"
    num_units: 3
    annotations: 
      "gui-x": "800"
      "gui-y": "550"
    to: 
      - "1"
      - "2"
      - "3"
  flannel: 
    charm: "cs:~containers/flannel-13"
    annotations: 
      "gui-x": "450"
      "gui-y": "750"
  kubeapi-load-balancer: 
    charm: "cs:~containers/kubeapi-load-balancer-10"
    num_units: 1
    expose: true
    annotations: 
      "gui-x": "450"
      "gui-y": "250"
    to: 
      - "4"
  kubernetes-master: 
    charm: "cs:~containers/kubernetes-master-17"
    num_units: 1
    annotations: 
      "gui-x": "800"
      "gui-y": "850"
    to: 
      - "5"
  kubernetes-worker: 
    charm: "cs:~containers/kubernetes-worker-22"
    num_units: 3
    expose: true
    annotations: 
      "gui-x": "100"
      "gui-y": "850"
    to: 
      - "6"
      - "7"
      - "8"
relations: 
  - - "kubernetes-master:kube-api-endpoint"
    - "kubeapi-load-balancer:apiserver"
  - - "kubernetes-master:loadbalancer"
    - "kubeapi-load-balancer:loadbalancer"
  - - "kubernetes-master:kube-control"
    - "kubernetes-worker:kube-control"
  - - "kubernetes-master:certificates"
    - "easyrsa:client"
  - - "etcd:certificates"
    - "easyrsa:client"
  - - "kubernetes-master:etcd"
    - "etcd:db"
  - - "kubernetes-worker:certificates"
    - "easyrsa:client"
  - - "kubernetes-worker:kube-api-endpoint"
    - "kubeapi-load-balancer:website"
  - - "kubeapi-load-balancer:certificates"
    - "easyrsa:client"
  - - "flannel:etcd"
    - "etcd:db"
  - - "flannel:cni"
    - "kubernetes-master:cni"
  - - "flannel:cni"
    - "kubernetes-worker:cni"
machines: 
  "0": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "1": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "2": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "3": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "4": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "5": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "6": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "7": 
    series: !<tag:yaml.org,2002:js/undefined> ""
  "8": 
    series: !<tag:yaml.org,2002:js/undefined> ""

```

While those **series** annotations may be valid other parsing libraries may not be able to import (like what is happening with PyYAML and conjure-up). 

```
$ cat conjure-up.log 
2017-05-02 15:39:21,695 [DEBUG] conjure-up/_unspecified_spell - app.py:221 - LXD version: 2.13, Juju version: 2.2-beta3-xenial-amd64, conjure-up version: 2.2-beta3+996471d
2017-05-02 15:39:21,705 [DEBUG] conjure-up/cdk-with-gestalt - download.py:60 - Path is local filesystem, copying conjure-up-spells/cdk-with-gestalt/ to /home/ericgf/.cache/conjure-up/cdk-with-gestalt
2017-05-02 15:39:21,721 [INFO] conjure-up/cdk-with-gestalt - events.py:107 - Watching for shutdown
2017-05-02 15:39:21,733 [DEBUG] conjure-up/cdk-with-gestalt - events.py:18 - Setting Error
2017-05-02 15:39:21,733 [ERROR] conjure-up/cdk-with-gestalt - events.py:96 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/245/lib/python3.6/site-packages/conjureup/events.py", line 94, in handle_exception
    raise exc
  File "/snap/conjure-up/245/lib/python3.6/site-packages/conjureup/app.py", line 123, in _start
    utils.setup_metadata_controller()
  File "/snap/conjure-up/245/lib/python3.6/site-packages/conjureup/utils.py", line 394, in setup_metadata_controller
    bundle_data = yaml.load(bundle_filename.read_text())
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/snap/conjure-up/245/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:js/undefined'
  in "<unicode string>", line 80, column 13:
        series: !<tag:yaml.org,2002:js/undefined> ""
```

Could we make sure the exported bundles can be read by the majority of parsers out there by not including these type of annotations?

**Comment by hatched** [comment]
@battlemidget This is a known bug in the GUI, can you confirm that you're exporting the bundle without deploying to a real cloud?

**Comment by hatched** [comment]
GUI bug: https://github.com/juju/juju-gui/issues/2801

**Comment by adam-stokes** [comment]
@hatched Yea this was from a user who was just creating a custom bundle to use with conjure-up and never made it to deploying to a cloud.
